### ISSUE TITLE
Error: "Please add devise :omniauthable"

### ISSUE THREAD

**Issue by MindRave** [solidusio-contrib/solidus_social#20]
Hi everyone!

Thanks for the great gem. I'm getting this little error every once in a while.

`Mapping omniauth_callbacks on a resource that is not omniauthable Please add`devise :omniauthable`to the`Spree::User`model`

Then, afterwards (sometimes), an entire multitude of stuff appears. One example:
`undefined method`nested_taxons_path' for #ActionDispatch::Routing::RoutesProxy:0x007fb15e9e5068``
 (simply on the root, out of nowhere)

Rails 5. Freshly new Solidus installation, everything by the book, nothing special. I restart the server, everything goes back to normal. I work some more, make some small changes and... This.

I don't get it.

**Comment by jarednorman** [comment]
Are you experiencing this in development or production?

(That following was misclick. Absolutely did not mean to close your issue :smiley:.)

**Comment by MindRave** [comment]
@jarednorman Development. Just started, and this started happening. Do you want the full error trace or my detailed Gemfile (basic, though, as I said)? Any other info I can provide?

**Comment by jarednorman** [comment]
Stack trace and Gemfile[.lock] might help. A link to the repo if it's public would be fine too.

**Comment by MindRave** [comment]
@jarednorman 

Here they are!

Stack trace:
https://gist.github.com/MindRave/28b9fca98fcf750f4bc724d99609a109

Gemfile.lock
https://gist.github.com/MindRave/9ee0b6b0eb8dfc45b6041e51b5cc3ed0

**Comment by jarednorman** [comment]
Interesting. Looks like some kind of code reloading issue. You aren't doing anything unusual in how you're decorating or handling `Spree::User` (if you're playing with it at all)?

**Comment by MindRave** [comment]
Nothing special, no. I just started playing around with Solidus and added an override to test Deface, but it's a standard Spree override (app/overrides/temp_text.rb), nothing fancy...

`Deface::Override.new(
  virtual_path: 'spree/user_registrations/new',
  name: 'temp_text',
  insert_after: '[data-hook="login_extras"]',
  text: 'Testing text',
  disabled: false
)`

**Comment by jarednorman** [comment]
Deface shouldn't be able to do any damage here.

**Comment by MindRave** [comment]
@jarednorman Decided to try with Spree and spree_social. Getting the same error (just by adding a Deface override)... Either it's something on my end or the spree_social gem (if I understand correctly, the solidus_social is a fork of spree_social). I'll either disable the social auth for now, or try and find another solution altogether (developing like this is impossible 😞 ).

If you don't have any ideas, thank you for your help! 😄

**Comment by flyfy1** [comment]
For anyone interested in looking into this issue further, I've created a vanilla solidus and replicated the issue: <https://github.com/flyfy1/VanillaSolidus>.

Basically, as long as I include the `solidus_social` gem, the error would popup.

**Comment by flyfy1** [comment]
OK my colleague and I has figured out the issue. It's due to rails 5 reload order change.

In Rails 5, when the reload happens, it's following the following steps:

1. unload the classes;
2. load the Routes first; if there're any object not loaded / unloaded, load them
3. and then reload the classes & decorators.

However, the decorator in SolidusSocial is trying to add in `omniauthable` into the User class, by re-defining devise in the class. Since it's not loaded at the time when routes is defined for devise, the routes would complain (therefore u can see the error above).

There's a quick fix: force the re-loading of models & decorators, before the routes. I've included the fix [in this commit](https://github.com/flyfy1/VanillaSolidus/commit/22e24fc75de2e04c7b84124ddcef33d7c2b86458).
