### ISSUE TITLE
facebook and google login not working

### ISSUE THREAD

**Issue by Homeshchopra94** [solidusio-contrib/solidus_social#32]
i am getting Could not authenticate you from Facebook because "Invalid credentials". for facebook and for google Could not authenticate you from Google oauth2 because "Invalid credentials".i have checked all the keys in the social authentication method but unable to find the reason.

**Comment by jarednorman** [comment]
What version of solidus_social and solidus are you using?

**Comment by Homeshchopra94** [comment]
solidus_social 1.0.0

**Comment by jarednorman** [comment]
And Solidus itself?

**Comment by jarednorman** [comment]
What does your `config/initializers/solidus_social.rb` look like? (Don't forget to censor your actual keys, if they are hardcoded.)

**Comment by jarednorman** [comment]
Closing this due to going two weeks without reply. Happy to re-open it if more information is provided. Cheers! :smiley:

**Comment by abhayathapa** [comment]
Hi can you provide details on Facebook login. I dont know what im missing.

I get this error `This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings. Make sure that the client and web OAuth logins are on and add all your app domains as valid OAuth redirect URIs.`

The url i used is `<%= link_to "Login with FB", "/users/auth/facebook" %>`

I have added  facebook  keys on solidus_social.rb
api_key: 342367450747827,
api_secret....

Am i Missing something. I tried with ngrok and localhost both for development but failed in both
